/**
 * Check BFSI workflow configuration
 */

import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

async function main() {
  console.log('🔍 Checking BFSI Workflow Configuration...\n');

  const workflow = await prisma.workflow.findFirst({
    where: {
      name: 'BFSI Marketing Campaign with Compliance',
    },
  });

  if (!workflow) {
    console.log('❌ Workflow not found');
    return;
  }

  const definition = workflow.definition as any;

  console.log('📝 Workflow Nodes:\n');

  definition.nodes.forEach((node: any, index: number) => {
    console.log(`${index + 1}. ${node.label} (${node.type})`);

    if (node.type === 'ai_content_generator') {
      console.log('\n   🤖 AI Content Generator Configuration:');
      console.log('   ─'.repeat(50));
      console.log(`   Content Type: ${node.config.contentType}`);
      console.log(`   Purpose: ${node.config.purpose}`);
      console.log(`   Target Audience: ${node.config.targetAudience}`);
      console.log(`   Tone: ${node.config.tone}`);
      console.log(`   Max Length: ${node.config.maxLength} characters`);
      console.log('\n   Key Points:');
      node.config.keyPoints.forEach((point: string, i: number) => {
        console.log(`   ${i + 1}. ${point}`);
      });
      console.log('   ─'.repeat(50));
    }

    if (node.type === 'whatsapp') {
      console.log('\n   📱 WhatsApp Configuration:');
      console.log('   ─'.repeat(50));
      console.log(`   To: ${node.config.to}`);
      console.log(`   Message Template: ${node.config.message}`);
      console.log(`   Credential ID: ${node.config.credentialId || 'NOT SET'}`);
      console.log('   ─'.repeat(50));
    }

    if (node.type === 'compliance_checker') {
      console.log('\n   ✅ Compliance Checker Configuration:');
      console.log('   ─'.repeat(50));
      console.log(`   Content Field: ${node.config.contentField}`);
      console.log(`   Content Type: ${node.config.contentType}`);
      console.log(`   Product Category: ${node.config.productCategory}`);
      console.log(`   Minimum Score: ${node.config.minimumScore}`);
      console.log('   ─'.repeat(50));
    }

    console.log('');
  });

  console.log('\n📊 Expected Flow:\n');
  console.log('1. AI generates professional credit card marketing content');
  console.log('2. Compliance checker validates the content');
  console.log('3. If compliant (score < 50), WhatsApp message is sent');
  console.log('4. Message contains AI-generated content with disclaimers\n');

  console.log('💬 Sample Expected WhatsApp Message:\n');
  console.log('─'.repeat(60));
  console.log('🎉 Exclusive Premium Credit Card Offer\n');
  console.log('Enjoy exceptional benefits:');
  console.log('✓ 0% APR for the first 12 months');
  console.log('✓ 5% cashback on dining and travel');
  console.log('✓ Complimentary airport lounge access');
  console.log('✓ No annual fee for the first year\n');
  console.log('Apply now and elevate your lifestyle!\n');
  console.log('Subject to eligibility criteria.');
  console.log('Terms and conditions apply.\n');
  console.log('Reply STOP to opt-out.');
  console.log('─'.repeat(60));
  console.log('\n(Actual content will be generated by Gemini AI and may vary)\n');
}

main()
  .catch((e) => {
    console.error('❌ Error:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
