/**
 * Show what message will be sent via WhatsApp
 */

import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

async function main() {
  const workflow = await prisma.workflow.findFirst({
    where: {
      name: 'BFSI Marketing Campaign with Compliance',
    },
  });

  if (!workflow) {
    console.log('❌ Workflow not found');
    return;
  }

  const definition = workflow.definition as any;

  // Find the nodes
  const aiNode = definition.nodes.find((n: any) => n.type === 'ai_content_generator');
  const whatsappNode = definition.nodes.find((n: any) => n.type === 'whatsapp');

  console.log('╔═══════════════════════════════════════════════════════════════╗');
  console.log('║       WhatsApp Message Content - BFSI Workflow               ║');
  console.log('╚═══════════════════════════════════════════════════════════════╝\n');

  console.log('📱 Recipient: +918610560986\n');

  console.log('🤖 Content Source: AI-Generated by Gemini\n');

  console.log('📋 AI Prompt Configuration:');
  console.log('─'.repeat(65));
  console.log(JSON.stringify(aiNode.config, null, 2));
  console.log('─'.repeat(65));

  console.log('\n\n💬 WhatsApp Node Configuration:');
  console.log('─'.repeat(65));
  console.log(`To: ${whatsappNode.config.to}`);
  console.log(`Message Template: ${whatsappNode.config.message}`);
  console.log(`Credential ID: ${whatsappNode.config.credentialId}`);
  console.log('─'.repeat(65));

  console.log('\n\n📝 What Gets Sent:\n');
  console.log('The WhatsApp message will contain:');
  console.log('1. AI-generated marketing content (from Gemini)');
  console.log('2. Based on the configuration above');
  console.log('3. The variable {{generatedContent}} will be replaced with actual AI output\n');

  console.log('💡 Expected Message Structure:\n');
  console.log('═'.repeat(65));
  console.log('🎉 [AI-Generated Headline]\n');
  console.log('[Professional introduction]\n');
  console.log('Benefits:');
  console.log('✓ 0% APR for first 12 months');
  console.log('✓ 5% cashback on dining and travel');
  console.log('✓ Complimentary airport lounge access');
  console.log('✓ No annual fee for first year\n');
  console.log('[Call to action]\n');
  console.log('Subject to eligibility criteria.');
  console.log('Terms and conditions apply.\n');
  console.log('Reply STOP to opt-out.');
  console.log('═'.repeat(65));

  console.log('\n\n⚠️  Note: The exact message content is generated by Gemini AI');
  console.log('   and will be professional, compliant, and engaging.\n');

  console.log('🔍 To see the actual message that will be sent:');
  console.log('   1. Run the workflow');
  console.log('   2. Check backend logs for "[AI] Content generated"');
  console.log('   3. The generated content will be shown in the logs\n');
}

main()
  .catch((e) => {
    console.error('❌ Error:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
